name: Tera Next

on:
  push:
    branches:
      - 'main'
  workflow_dispatch:

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - uses: docker/setup-buildx-action@v3
      - uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - uses: docker/build-push-action@v6
        with:
          file: ./apps/tera-next/Dockerfile
          push: true
          tags: ${{ vars.DOCKERHUB_USERNAME }}/tera:next
          cache-from: type=gha
          cache-to: type=gha,mode=max
